env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module
plugins:
  - react
  - import
  - jsx-a11y
  - react-hooks
rules:
  react/prop-types: 0
  react/react-in-jsx-scope: 0
settings:
  import/resolver:
    node:
      paths: ["./winiskapi/static/src"]
      extensions: [".js", ".jsx"]
