"""empty message

Revision ID: 2af18d0a84eb
Revises: f13818d6878e
Create Date: 2022-03-03 18:13:29.937099

"""

# revision identifiers, used by Alembic.
revision = "2af18d0a84eb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'uid', nullable=False, new_column_name='id')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'id', nullable=False, new_column_name='uid')
    # ### end Alembic commands ###
